# Generated by Django 4.1 on 2022-08-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="created_at",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
